services:
#    redacted_passwordless.example:
#        class: Redacted\PasswordlessBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  redacted.security.authentication.provider:
        class: Redacted\PasswordlessBundle\Security\Authentication\Provider\RedactedProvider
        arguments: []

  redacted.security.authentication.listener:
      class: Redacted2\PasswordlessBundle\Security\Firewall\RedactedListener
      arguments: ["@security.token_storage", "@security.authentication.manager"]

  redacted_passwordless_cache:
    class: Redacted\PasswordlessBundle\Services\CacheService

  redacted_passwordless_token:
    class: Redacted\PasswordlessBundle\Services\TokenService

  redacted_passwordless_email:
    class: Redacted\PasswordlessBundle\Services\EmailService
    arguments: [@mailer, @templating]

